### ISSUE TITLE
Missing binaries for platform toolset v143

### ISSUE THREAD

**Issue by lnx00** [sgrottel/nuget-lua#1]
It seems that there are no binaries for the platform toolset v143 and this NuGet package can thus not be used with the latest version of Visual Studio (2022).

**Comment by HanaMcHanaface** [comment]
Yep same problem

**Comment by sgrottel** [comment]
I have no idea why i missed you opening this issue. Sorry!
I will look into this right away.

**Comment by sgrottel** [comment]
Fixed: https://github.com/sgrottel/nuget-lua/commit/a32dbd4ac446220029aa2d53e0fe16457f03ebff
