### ISSUE TITLE
LLVM Support

### ISSUE THREAD

**Issue by romanf-dev** [sgrottel/nuget-lua#15]
Hello,
Setting "Project properties" ("Configuration Properties\General\Platform Toolset") in Visual Studio 2022 to "LLVM (clang-cl)" leads to linker error:
lld-link: error: could not open 'C:\Project\threaded\packages\lua.5.4.7\build\native\lib\x64\ERROR\Release\lua.lib': no such file or directory

**Comment by sgrottel** [comment]
Yes, I can confirm, the current nuget package is not compatible with the LLVM toolset.

I will prepare a fix and a patch release.

**Comment by sgrottel** [comment]
@romanf-dev , please try the following as workaround until I can supply a package update release with proper LLVM-Support:

- Open the "Project properties"
- Go to "Referenced Packages" > "Lua"
- Change "Runtime Platform" from "Default" to "v143"

Please, tell me if that works for you, and unblocks you.
(Even if that works for you, leave this issue open. I will introduce _real_ ClangCL support into the package.)

**Comment by romanf-dev** [comment]
Thank you! The workaround works well.

**Comment by sgrottel** [comment]
Upcoming patch release 5.4.7.1 introduces ClangCL-built binaries

**Comment by romanf-dev** [comment]
Still the same error after update to the latest package
