### ISSUE TITLE
LLVM support

### ISSUE THREAD

**Issue by romanf-dev** [sgrottel/nuget-lua#17]
Can't reopen the issue #15 so this is the new one. Still the same error after update to the latest version 5.4.7.1.

**Comment by sgrottel** [comment]
Oh. How did I miss that? Sorry!

Please, check the new Nuget v5.4.7.2

I will leave this ticket open until you confirm that the new nuget is working for you.

**Comment by romanf-dev** [comment]
It works now, thank you a lot!
